FROM debian:buster

RUN apt-get update -y
RUN apt-get upgrade -y

RUN apt-get install -y php

RUN apt-get install -y php-fpm

RUN apt-get install -y php-mysql \
RUN apt-get install -y php-mysqli

#Install mariadb to link with Database
RUN apt-get install -y mariadb-client

